"""Initial migration: patients, scan_records, medecins, consultations

Revision ID: 001_initial
Revises: 
Create Date: 2025-06-21

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nom', sa.String(length=255), nullable=False),
        sa.Column('prenom', sa.String(length=255), nullable=False),
        sa.Column('date_naissance', sa.DateTime(), nullable=True),
        sa.Column('genre', sa.String(length=10), nullable=True),
        sa.Column('tel', sa.String(length=20), nullable=True),
        sa.Column('poids', sa.Float(), nullable=True),
        sa.Column('taille', sa.Float(), nullable=True),
        sa.Column('FC', sa.Integer(), nullable=True),
        sa.Column('glycemie', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medecins',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nom', sa.String(length=255), nullable=False),
        sa.Column('prenom', sa.String(length=255), nullable=False),
        sa.Column('specialite', sa.String(length=255), nullable=True),
        sa.Column('tel', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('departement', sa.String(length=255), nullable=True),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('password', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    op.create_table('scan_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=100), nullable=False),
        sa.Column('scan_date', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('classification', sa.String(length=100), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('tumor_area_mm2', sa.Float(), nullable=True),
        sa.Column('max_diameter_mm', sa.Float(), nullable=True),
        sa.Column('tumor_location', sa.String(length=255), nullable=True),
        sa.Column('clinical_summary', sa.Text(), nullable=True),
        sa.Column('review_status', sa.String(length=50), server_default='pending_review', nullable=True),
        sa.Column('reviewed_by', sa.String(length=100), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('session_id')
    )
    op.create_table('consultations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('medecin_id', sa.Integer(), nullable=False),
        sa.Column('scan_record_id', sa.Integer(), nullable=True),
        sa.Column('date_consultation', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('motif', sa.String(length=500), nullable=True),
        sa.Column('diagnostic', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('rapport_genere', sa.Text(), nullable=True),
        sa.Column('statut', sa.String(length=50), server_default='en_cours', nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=True),
        sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['scan_record_id'], ['scan_records.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultations')
    op.drop_table('scan_records')
    op.drop_table('medecins')
    op.drop_table('patients')
    # ### end Alembic commands ###
