server.port=8080
spring.application.name=spring-backend

# Disable basic error page
server.error.include-message=always

# Python AI Service URL (Local execution)
python.service.url=http://localhost:8000

# MySQL Shared Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/medical_ai?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rabiestar@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Limits (For large MRI files)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
